apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotstar-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hotstar.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hotstar-service
            port:
              number: 80
